apiVersion: v1
kind: Service
metadata:
  name: query-node
  namespace: graph-mainnet
spec:
  selector:
    app: query-node
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
    - name: http-status
      protocol: TCP
      port: 8030
      targetPort: 8030
