
name: package poker

on: workflow_dispatch


env:
  IMAGE_NAME: metaops/camunda-diy-poker
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: docker build
      run:  docker build . --file Dockerfile.poker --tag ${{ env.IMAGE_NAME }}:latest

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker push
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.IMAGE_NAME }}:latest

