
name: package poker

on: workflow_dispatch


env:
  IMAGE_NAME: metaops/camunda-diy-poker
  DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
        echo $RELEASE_VERSION
        echo ${{ env.RELEASE_VERSION }}    
    - name: create latest tag if its the main branch
      if:  ${{ env.RELEASE_VERSION == 'main' }}
      run: echo "DOCKER_TAG=latest" >> $GITHUB_ENV  
    - name: create git tag if its the build uses tag
      if:  ${{ env.RELEASE_VERSION != 'main' }}
      run: echo "DOCKER_TAG=${{ env.RELEASE_VERSION }}" >> $GITHUB_ENV  

    - name: docker build
      run:  docker build . --file Dockerfile.poker --tag ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: docker push
      if: github.event_name != 'pull_request'
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}

